# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{elibri_api_client}
  s.version = "1.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcin Urba\305\204ski"]
  s.date = %q{2011-10-18}
  s.description = %q{API client for elibri.com.pl publishing system}
  s.email = %q{marcin@urbanski.vdl.pl}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "elibri_api_client.gemspec",
    "lib/elibri_api_client.rb",
    "lib/elibri_api_client/api_adapters.rb",
    "lib/elibri_api_client/api_adapters/v1.rb",
    "lib/elibri_api_client/api_adapters/v1_helpers.rb",
    "lib/elibri_api_client/core_extensions.rb",
    "lib/elibri_api_client/version.rb",
    "test/elibri_api_client_test.rb",
    "test/elibri_api_v1_adapter_product_test.rb",
    "test/elibri_api_v1_adapter_publisher_test.rb",
    "test/elibri_api_v1_adapter_queue_pop_test.rb",
    "test/elibri_api_v1_adapter_queue_test.rb",
    "test/elibri_api_v1_adapter_test.rb",
    "test/helper.rb"
  ]
  s.homepage = %q{http://github.com/elibri/elibri_api_client}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{API client for elibri.com.pl publishing system}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["= 0.8.1"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.5.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<elibri_onix>, [">= 0.1.5"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, ["= 0.8.1"])
      s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<elibri_onix>, [">= 0.1.5"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, ["= 0.8.1"])
    s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<elibri_onix>, [">= 0.1.5"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

